### ISSUE TITLE
.Call() function error?

### ISSUE THREAD

**Issue by jeanvuda** [nacnudus/tidyxl#23] opened 2017-11-21 17:52 UTC
It seems an amazing project and I wanted to give it a try:
```
library(tidyxl)
titanic <- system.file("extdata/titanic.xlsx", package = "tidyxl")
x <- tidyxl::xlsx_cells(titanic, sheets="Sheet1")
```
Gives the following error.

```
Error in .Call("_tidyxl_xlsx_sheet_files_", PACKAGE = "tidyxl", path) : 
  "_tidyxl_xlsx_sheet_files_" not available for .Call() for package "tidyxl"
```

Here is my sessioninfo.
```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.12         tidyxl_1.0.0         RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] assertthat_0.2.0 digest_0.6.12    dplyr_0.7.4      withr_2.0.0      cellranger_1.1.0 R6_2.2.0         magrittr_1.5    
 [8] rlang_0.1.2.9000 bindrcpp_0.2     devtools_1.13.3  RevoUtils_10.0.4 tools_3.4.0      glue_1.1.1       yaml_2.1.14     
[15] compiler_3.4.0   pkgconfig_2.0.1  memoise_1.1.0    bindr_0.1        tibble_1.3.4  
```
In addition to that, I had to install "piton" dependency. May be worth to mention it in the example?
```
devtools::install_github("ironholds/piton")
devtools::install_github("nacnudus/tidyxl")
```

**Comment by nacnudus** [comment] 2017-11-21 22:59
Hi @jeanvuda, thanks for trying it out!

The error is strange.  Normally the piton package would be installed automatically, because it is among the dependencies in the `DESCRIPTION` FILE, and it is on CRAN.  Perhaps the installation didn't complete properly.  Have you tried reinstalling?

**Comment by nacnudus** [comment] 2017-12-08 00:29
Closing as I cannot reproduce the error.

**Closed by nacnudus** 2017-12-08 00:29 UTC
