### ISSUE TITLE
special characters in sheet names

### ISSUE THREAD

**Issue by luisDVA** [nacnudus/tidyxl#37] opened 2018-06-08 04:09 UTC
Hi Duncan,
I was working with some xlsx files that had sheet names in Spanish and I noticed that the names with special characters were getting garbled in the 'sheet' variable of the output data frame. I'm assuming it's an encoding issue. Is this something that could be specified as an argument during the file import? 

thanks for the package!

**Comment by nacnudus** [comment] 2018-06-08 06:55
Hi!  I thought this was fixed in #12.  Can you provide an example?  I've just tested with `µ`, and it works.

**Comment by luisDVA** [comment] 2018-06-08 16:54
I just tried to recreate the issue on my work computer (running Linux Mint) but now the sheet names show up fine. The garbling seems to only happen in Windows, I need to check on a different machine.

**Comment by nacnudus** [comment] 2018-06-08 17:46
Ah, Windows. What version? I have a bad feeling this came up before and I took a shortcut hoping it would go away.

**Comment by luisDVA** [comment] 2018-06-08 18:55
I run a Windows 10 partition. I'll get the session info for my laptop and for my collaborator's system.

**Comment by nacnudus** [comment] 2018-06-08 23:56
Thanks. I'm about to be offline for a week but I will get back to this.

**Comment by nacnudus** [comment] 2018-06-26 15:31
I can't reproduce this with `µ` on Windows 10 so I'll close the issue.  Feel free to reopen with a reproducible example.

**Closed by nacnudus** 2018-06-26 15:31 UTC

**Comment by luisDVA** [comment] 2018-06-26 15:36
I was also unable to reproduce this on Windows 10 and couldn't track down the student that was having issues with the encoding. Thanks for the replies!
